name: Deploy React App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd react-app
          npm install

      - name: Build React app
        run: |
          cd react-app
          npm run build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: YourReactAppServiceName
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_REACT }}
          package: ./react-app/build
