name: Deploy C# Web API

on:
  push:
    branches:
      - main  # כל push ל-main יפעיל את workflow

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. Checkout הקוד
      - uses: actions/checkout@v4

      # 2. Setup .NET
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build
      - name: Build
        run: dotnet build --configuration Release

      # 5. Publish
      - name: Publish
        run: dotnet publish -c Release -o published

      # 6. Deploy to Azure Web App
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <C#_AppService_Name>
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_CSHARP }}
          package: ./published
